# Translation Catalog for English and Persian (RTL support included)
TRANSLATIONS = {
    "en": {
        "title": "ConfigFlow",
        "login_title": "Sign in to your account",
        "login_subtitle": "Manage and deploy service configurations elegantly",
        "username": "Username",
        "password": "Password",
        "sign_in": "Sign In",
        "logout": "Logout",
        "logged_in_as": "Logged in as",
        "step": "Step",
        "of": "of",
        "wizard_title": "Service Configuration",
        "wizard_subtitle": "Please fill in the details below to deploy your configuration.",
        "customer_section": "Customer Profile",
        "customer_section_desc": "Enter the customer details for this configuration.",
        "prefill_title": "Use previous customer details?",
        "prefill_btn": "Prefill",
        "prefilled_btn": "Prefilled!",
        "customer_date": "Date",
        "customer_name": "Customer Name",
        "certificate_id": "Certificate ID",
        "customer_place": "Place",
        "machine_name": "Machine Name",
        "back": "Back",
        "forward": "Forward",
        "submit": "Submit Configuration",
        "success_title": "Configuration Submitted",
        "success_subtitle": "Successfully created and saved service configuration for",
        "submitted_details": "Just Submitted Service Configuration",
        "configure_another": "Configure Another Service",
        "sign_out": "Sign Out",
        "error_login": "Invalid username or password. Please try admin/admin.",
        # Test Selection
        "select_test_title": "Select Test Configuration",
        "select_test_desc": "Search and choose between the available test configurations below.",
        "search_test_placeholder": "Search tests (e.g. Test A, Test B...)",
        "selected_test_label": "Selected Test",
        # Parameter labels
        "Database Host": "Database Host",
        "Database Port": "Database Port",
        "API Key": "API Key",
        "Max Retries": "Max Retries",
        "Timeout (seconds)": "Timeout (seconds)",
        "Database Replica Host": "Database Replica Host",
        "Port": "Port",
        "Read Cache Size (MB)": "Read Cache Size (MB)",
        "Use SSL (Yes/No)": "Use SSL (Yes/No)",
        "API Endpoints Base": "API Endpoints Base",
        "Request Interval (ms)": "Request Interval (ms)",
        "Retry Interval (ms)": "Retry Interval (ms)",
        "Auth Strategy": "Auth Strategy",
        "Machine Target IP": "Machine Target IP",
        "Operation Frequency (Hz)": "Operation Frequency (Hz)",
        "Safety Protocol Version": "Safety Protocol Version",
        "Operator Code": "Operator Code",
        # Submissions page
        "submissions_title": "Submitted Configurations",
        "submissions_subtitle": "Review and export all configured test scenarios and profiles.",
        "download_csv": "Download CSV",
        "no_submissions": "No submissions found yet.",
        "nav_submissions": "Submissions",
        "nav_wizard": "Config Wizard",
        "table_customer": "Customer / Organ",
        "table_test": "Test Profile",
        "table_params": "Parameters",
        "table_actions": "Actions",
        "view_wizard_btn": "Go to Configurator"
    },
    "fa": {
        "title": "جریان پیکربندی",
        "login_title": "ورود به حساب کاربری",
        "login_subtitle": "پیکربندی خدمات خود را به زیبایی مدیریت و مستقر کنید",
        "username": "نام کاربری",
        "password": "رمز عبور",
        "sign_in": "ورود",
        "logout": "خروج",
        "logged_in_as": "وارد شده به عنوان",
        "step": "مرحله",
        "of": "از",
        "wizard_title": "پیکربندی سرویس",
        "wizard_subtitle": "لطفاً جزئیات زیر را برای استقرار پیکربندی خود وارد کنید.",
        "customer_section": "پروفایل مشتری",
        "customer_section_desc": "مشخصات سازمان مشتری را برای این پیکربندی وارد کنید.",
        "prefill_title": "استفاده از اطلاعات مشتری قبلی؟",
        "prefill_btn": "تکمیل خودکار",
        "prefilled_btn": "تکمیل شد!",
        "customer_date": "تاریخ",
        "customer_name": "نام مشتری",
        "certificate_id": "شناسه گواهینامه",
        "customer_place": "محل",
        "machine_name": "نام دستگاه",
        "back": "قبلی",
        "forward": "بعدی",
        "submit": "ثبت پیکربندی",
        "success_title": "پیکربندی با موفقیت ثبت شد",
        "success_subtitle": "پیکربندی سرویس با موفقیت ایجاد و برای مشتری ذخیره شد:",
        "submitted_details": "پیکربندی سرویس ارسال شده",
        "configure_another": "پیکربندی یک سرویس دیگر",
        "sign_out": "خروج از سیستم",
        "error_login": "نام کاربری یا رمز عبور نامعتبر است. لطفا admin/admin را امتحان کنید.",
        # Test Selection
        "select_test_title": "انتخاب پیکربندی تست",
        "select_test_desc": "پیکربندی تست مورد نظر خود را از میان موارد زیر جستجو و انتخاب کنید.",
        "search_test_placeholder": "جستجوی تست‌ها (مانند تست الف، تست ب...)",
        "selected_test_label": "تست انتخاب شده",
        # Parameter labels
        "Database Host": "آدرس پایگاه داده",
        "Database Port": "پورت پایگاه داده",
        "API Key": "کلید API",
        "Max Retries": "حداکثر دفعات تلاش",
        "Timeout (seconds)": "زمان انتظار (ثانیه)",
        "Database Replica Host": "آدرس پایگاه داده فرعی (Replica)",
        "Port": "پورت اتصال",
        "Read Cache Size (MB)": "اندازه حافظه نهان خواندن (مگابایت)",
        "Use SSL (Yes/No)": "استفاده از پروتکل SSL (بله/خیر)",
        "API Endpoints Base": "آدرس پایه پایانه API",
        "Request Interval (ms)": "فاصله زمانی درخواست (میلی‌ثانیه)",
        "Retry Interval (ms)": "فاصله زمانی تلاش مجدد (میلی‌ثانیه)",
        "Auth Strategy": "روش احراز هویت",
        "Machine Target IP": "آدرس IP دستگاه هدف",
        "Operation Frequency (Hz)": "فرکانس کاری دستگاه (هرتز)",
        "Safety Protocol Version": "نسخه پروتکل ایمنی",
        "Operator Code": "کد اختصاصی اپراتور",
        # Submissions page
        "submissions_title": "پیکربندی‌های ثبت شده",
        "submissions_subtitle": "بررسی و خروجی گرفتن از تمام سناریوها و فایل‌های پیکربندی تست.",
        "download_csv": "دانلود خروجی CSV",
        "no_submissions": "هنوز هیچ پیکربندی ثبت نشده است.",
        "nav_submissions": "لیست ثبت‌ها",
        "nav_wizard": "ویزارد پیکربندی",
        "table_customer": "مشتری / سازمان",
        "table_test": "پروفایل تست",
        "table_params": "پارامترهای تنظیم شده",
        "table_actions": "عملیات",
        "view_wizard_btn": "رفتن به پیکربندی"
    }
}

# Dynamic configurations for each available Test
TESTS_CONFIG = {
    "Test A": {
        "Database Host": "localhost",
        "Database Port": "5432",
        "API Key": "super-secret-api-key-123",
        "Max Retries": "5",
        "Timeout (seconds)": "30"
    },
    "Test B": {
        "Database Replica Host": "replica.db.local",
        "Port": "5433",
        "Read Cache Size (MB)": "256",
        "Use SSL (Yes/No)": "Yes"
    },
    "Test C": {
        "API Endpoints Base": "https://api.test-c.internal",
        "Request Interval (ms)": "1000",
        "Retry Interval (ms)": "5000",
        "Auth Strategy": "OAuth2-Bearer"
    },
    "Test D": {
        "Machine Target IP": "192.168.1.100",
        "Operation Frequency (Hz)": "50",
        "Safety Protocol Version": "v2.1.4",
        "Operator Code": "OP-901"
    }
}
